version: '3'

networks:
  monitoring:
    driver: ${DOCKER_NETWORKS_DRIVER}
  frontend:
    driver: ${DOCKER_NETWORKS_DRIVER}

services:
  portainer:
    image: portainer/portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKER_DATA_HOST_PATH}/portainer:/data
    ports:
      - 9000:9000
    networks:
      - frontend

  grafana:
    image: grafana/grafana
    volumes:
      - ${DOCKER_DATA_HOST_PATH}/grafana:/var/lib/grafana
    user: root
    ports:
      - 9001:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    networks:
      - monitoring
      - frontend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    volumes:
      - ./phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
    ports:
      - 9002:80
    environment:
      - PMA_HOSTS=${PMA_HOSTS}
      - PMA_PORTS=${PMA_PORTS}
      - PMA_ARBITRARY=${PMA_ARBITRARY}
    networks:
      - frontend

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - ${DOCKER_DATA_HOST_PATH}/prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    user: root
    ports:
      - 9050:9090
    networks:
      - monitoring

  cadvisor:
    image: google/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /dev/disk:/dev/disk:ro
    ports:
      - 9051:8080
    networks:
      - monitoring

  nodeexporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - 9052:9100
    networks:
      - monitoring